[project]
name = "llm-reinforcement"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "diffusers>=0.35.2",
    "requests>=2.32.5",
    "streamlit>=1.52.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "transformers>=4.57.3",
]
